version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always
    networks:
      - default
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=external"
      - "traefik.git.frontend.rule=Host:devlab.iutbeziers.org"
      - "traefik.git.port=80"
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: rtbz123
    networks:
      - default
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:

networks:
  default:
  external:
    external: true
