version: "3.4"

services:
  keycloak_db:
    image: postgres:11.2-alpine
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=[pass_here]
        - POSTGRES_ROOT_PASSWORD=[pass_here]
    networks:
      external:
    volumes:
      - ./data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  keycloak:
    image: jboss/keycloak:latest
    hostname: keycloak
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_DATABASE=keycloak
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=[pass_here]
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=[pass_here]
    networks:
      auth_internal:
      external:
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.docker.network=external
      - traefik.frontend.rule=Host:keycloak.iutbeziers.org
      - traefik.protocol=http
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]


networks:
  auth_internal:
    external: true
  external:
    external: true
