version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    hostname: git.iutbeziers.org
    healthcheck:
      disable: true
    networks:
    - internal
    - external
    environment:
      GITLAB_OMNIBUS_CONFIG: | 
        external_url 'https://git.iutbeziers.org'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['http2_enabled'] = false

        nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        gitlab_rails['gitlab_shell_ssh_port'] = 1022

        registry_external_url 'https://registry.git.iutbeziers.org'
        registry_nginx['listen_port'] = 5100
        registry_nginx['listen_https'] = false

        registry_nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        pages_external_url 'https://pages.git.iutbeziers.org'
        pages_nginx['listen_port'] = 5200
        pages_nginx['listen_https'] = false

        pages_nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        gitlab_pages['inplace_chroot'] = true
        gitlab_pages['external_http'] = ['gitlab:5201']
        
        
        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect']
        gitlab_rails['omniauth_sync_email_from_provider'] = 'openid_connect'
        gitlab_rails['omniauth_sync_profile_from_provider'] = ['openid_connect']
        gitlab_rails['omniauth_sync_profile_attributes'] = ['name', 'email']
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'openid_connect'
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails['omniauth_auto_link_ldap_user'] = true
        gitlab_rails['omniauth_auto_link_saml_user'] = false

        gitlab_rails['omniauth_providers'] = [
          {
            'name' => 'openid_connect',
            'label' => 'OpenID Connect Provider',
            'args' => {
              'name' => 'openid_connect',
              'scope' => ['openid','profile'],
              'response_type' => 'code',
              'issuer' => 'https://keycloak.iutbeziers.org/auth/realms/Tests',
              'discovery' => true,
              'client_auth_method' => 'query',
              'uid_field' => 'preferred_username',
              'client_options' => {
                'identifier' => 'git.iutbeziers.org',
                'secret' => '[secret_key]',
                'redirect_uri' => 'https://git.iutbeziers.org/users/auth/openid_connect/callback',
              }
            }
          }
        ]

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=external"
      - "traefik.git.frontend.rule=Host:git.iutbeziers.org"
      - "traefik.git.port=80"
      - "traefik.registry.frontend.rule=Host:registry.git.iutbeziers.org"
      - "traefik.registry.port=5100"
      - "traefik.pages.frontend.rule=Host:pages.git.iutbeziers.org,username.pages.git.iutbeziers.org"
      - "traefik.pages.port=5201"
    ports:
    - "1022:1022"
    volumes:
    - gitlab-config:/etc/gitlab
    - gitlab-logs:/var/log/gitlab
    - gitlab-data:/var/opt/gitlab
    
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner.toml:/etc/gitlab-runner/config.toml
    networks:
      - internal
    
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-data:

networks:
  external:
    external: true
  internal:
