concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "example runner"
  url = "https://git.iutbeziers.org/-/readiness?token=[token_here]"
  token = "[token_here]"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    # Add this line
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
